server.port=8081

# ===============================
# SQL SERVER CONFIG
# ===============================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=pps_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=Lavanya@32
spring.datasource.password=Gopibabu@39
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# DISABLE HIBERNATE (as you wanted)
# ===============================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# ===============================
# CONNECTION POOL (OPTIONAL)
# ===============================
spring.datasource.hikari.maximum-pool-size=10

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=INFO