# ===============================
# SERVER
# ===============================
server.port=8082

# ? VERY IMPORTANT (fix 415 + WebClient conflict)
spring.main.web-application-type=servlet

# ===============================
# PRODUCT SERVICE (WebClient)
# ===============================
product.service.url=http://localhost:8081

# ===============================
# DATABASE (SQL SERVER)
# ===============================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=pps_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=Lavanya@32
spring.datasource.password=Gopibabu@39
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# KAFKA CONFIG
# ===============================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.kafka=INFO
logging.level.org.hibernate.SQL=DEBUG