server.port=8081

# DB CONFIG
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=pps_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=Lavanya@32
spring.datasource.password=Gopibabu@39
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# KAFKA
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.microservices.pps.event.CartEvent